cmd, eth: use blockPollingInterval flag
livepeer/go-livepeer pull request #1133
Opened 2019-10-23 22:34 UTC by kyriediculous

**What does this pull request do? Explain your changes. (required)**
This PR removes different hardcoded polling intervals used for different services that query the blockchain periodically. Examples include `gasPriceMonitor`, `blockWatcher`,  `rewardService`, ... 
**Specific updates (required)**
- added a new flag `blockPollingInterval` that takes in an integer to indicate the polling interval in seconds
- remove all seperate hardcoded polling intervals in livepeer.go
- add a `pollingInterval` field to `RewardService` and set it to the `blockPollingInterval` when invoking the constructor

**How did you test each of these updates (required)**
Ran test-harness
Ran unit tests

**Does this pull request close any open issues?**
Fixes #1128 

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

2019-10-24 01:09 UTC, yondonfu requested changes
Looks good! Just one minor variable naming comment.

2019-10-24 01:09 UTC, yondonfu commented on cmd/livepeer/livepeer.go
> +	blockPollTime := flag.Int("blockPollingInterval", 5, "Interval in seconds at which different blockchain event services poll for blocks")
Can we use the same name for the variable and the flag to follow the convention used in the rest of the flags?

2019-10-24 22:31 UTC, yondonfu reviewed
Changes look good! Let's rebase.

2019-10-24 23:03 UTC, kyriediculous commented
rebased

2019-10-24 23:44 UTC, yondonfu approved these changes
LGTM!

2019-10-24 23:46 UTC, merged

2019-12-16 17:40 UTC, wohlner commented
Can you please delete this closed branch?