Documentation for the HTTP ingest
livepeer/go-livepeer pull request #1337
Opened 2020-01-31 00:12 UTC by darkdarkdragon

**What does this pull request do? Explain your changes. (required)**
Adds documentation for the HTTP ingest

**Specific updates (required)**

- 
- 
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

Fixes #1323 

**Checklist:**

- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [ ] All tests in `./test.sh` pass

2020-02-03 20:56 UTC, iameli requested changes
Solid, just did a round of copyediting.

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +Body of the request should be binary data of the MPEG TS segment.
```suggestion
The body of the request should be the binary data of the MPEG TS segment.
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +  * `Content-Resolution` - in ther format `widthxheight`, for example: `1920x1080`.
```suggestion
  * `Content-Resolution` - in the format `widthxheight`, for example: `1920x1080`.
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +  * `Content-Duration` - duration of segment, in milliseconds. Should be integer.
```suggestion
  * `Content-Duration` - duration of the segment, in milliseconds. Should be an integer.
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +URL should have this structure:
```suggestion
The upload URL should have this structure:
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +Where `movie` is name of the stream, `12` is the sequence number of the segment.
```suggestion
Where `movie` is name of the stream and `12` is the sequence number of the segment.
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +HLS manifest will be available at
```suggestion
The HLS manifest will be available at 
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +- 503 Service Unavailable - if broadcaster wasn't able to find orchestrator to transcode the segment
```suggestion
- 503 Service Unavailable - if the broadcaster wasn't able to find an orchestrator to transcode the segment
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +Optionally, actual transcoded segments or URLs to them can be returned in the response.
```suggestion
Optionally, actual transcoded segments or URLs pointing to them can be returned in the response.
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +If `multipart/mixed` specified in the `Accept` header, then `Content-Type` of the response will be set to `multipart/mixed`, and body will consist of 'parts', according to [RFC1341](https://www.w3.or
```suggestion
If `multipart/mixed` specified in the `Accept` header, then `Content-Type` of the response will be set to `multipart/mixed`, and the body will consist of 'parts', according to [RFC1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html). If external object storage is used by broadcaster, then each part will have `application/vnd+livepeer.uri` content type, and will contain URL for the transcoded segment. If no external object storage is used, then `Content-Type` of each part will be `video/MP2T`, and the body of the part will contain the actual transcoded segment.
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +Each part will also contain such headers:
```suggestion
Each part will also contain these headers:
```

2020-02-03 20:56 UTC, iameli commented on doc/ingest.md
> +- `Content-Length` - length of the part
```suggestion
- `Content-Length` - length of the part in milliseconds
```

2020-02-03 22:24 UTC, darkdarkdragon commented on doc/ingest.md
> +- `Content-Length` - length of the part
It is in bytes actually :)
fixed

2020-02-03 22:25 UTC, darkdarkdragon commented
@iameli Thanks! Meaning of those articles still escapes me :(
fixed

2020-02-05 20:21 UTC, iameli approved these changes
LGTM!

2020-02-05 21:03 UTC, merged