monitor, eth: log deposit and reserve for the broadcaster only when monitor is enabled
livepeer/go-livepeer pull request #1541
Opened 2020-06-17 00:36 UTC by kyriediculous

**What does this pull request do? Explain your changes. (required)**

Add statements for the monitoring package that log the reserve and deposit for a broadcaster when monitoring is enabled upon the senderWatcher receiving an event.

To make sure only events pertaining to the broadcaster are logged (and events are only logged when in broadcaster mode) we check whether the address for which the event was emitted is the current ETH client address.

**Specific updates (required)**
- Add necessary logic to `monitor` package 
- Adds calls to `monitor.Deposit()` and `monitor.Reserve()` in the `senderWatcher` 

**Does this pull request close any open issues?**
Fixes #1540 

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

2020-06-19 22:11 UTC, yondonfu requested changes

2020-06-19 22:11 UTC, yondonfu commented on eth/watchers/senderwatcher.go
> +		monitor.Reserve(sender.Hex(), new(big.Int).Add(sw.senders[sender].Reserve.FundsRemaining, sw.senders[sender].Reserve.ClaimedInCurrentRound))
We don't need to add `Reserve.ClaimedInCurrentRound` here since we just care about the amount of funds remaining in the broadcaster's reserve.

2020-06-19 22:11 UTC, yondonfu commented on eth/watchers/senderwatcher.go
> +	if sender == sw.lpEth.Account().Address && monitor.Enabled {
Just noting that deposit/reserve metrics will be logged for any of the events handled in the above switch statement. That seems ok for now since 4/6 of the events would trigger deposit/reserve metrics logging anyway and keeping this code block at the end of the function seems preferable to adding conditionals to only log deposit/reserve metrics for those 4 events.

2020-06-20 21:22 UTC, kyriediculous commented on eth/watchers/senderwatcher.go
> +		monitor.Reserve(sender.Hex(), new(big.Int).Add(sw.senders[sender].Reserve.FundsRemaining, sw.senders[sender].Reserve.ClaimedInCurrentRound))
fixed in 41750d3

2020-06-24 00:45 UTC, yondonfu reviewed
Changes look good - let's rebase.

2020-06-24 00:46 UTC, kyriediculous commented
rebased

2020-06-24 17:10 UTC, yondonfu approved these changes
LGTM :shipit:

2020-06-24 17:11 UTC, merged