Add support for H264 profiles
livepeer/go-livepeer pull request #1542
Opened 2020-06-19 07:18 UTC by jailuthra

**What does this pull request do? Explain your changes. (required)**
This PR adds support for specifying the H264 encoder profile (#1531) by passing it as a field in the VideoProfile related structs.

**Specific updates (required)**
- 1a4543e510e3eb154a8f15ea13eea37109b1f779 Add the field in Protobuf `net.VideoProfile` struct - Serialize/Deserialize to LPMS VideoProfile
- 1298f091555145b690dc973c1ecc2825c96661e3 Back Compat with older Os by using `FullProfiles3` field only when the new Profiles field is used
- 1786a39c82c95a97ee9919a572c5857ba0417f71 Add ability to configure the H264 profile from the auth webhook JSON response

**How did you test each of these updates (required)**

- Unit Tests for new codepaths
- Manual testing with off-chain B-OT setup

**Does this pull request close any open issues?**

Fixes #1531 

**Checklist:**

- [x] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

2020-06-22 19:45 UTC, j0sh requested changes

2020-06-22 19:45 UTC, j0sh commented on go.sum
> +github.com/livepeer/lpms v0.0.0-20200619063758-7ae8da134ed4 h1:/0dAE31cmZEHMrmuL/DrAp6Cys++9F9+8eC8ZaSvYyQ=
`go mod tidy` will remove the older LPMS lines

2020-06-22 19:45 UTC, j0sh commented on common/util.go
> +func EncoderProfileNameToValue(profile string) ffmpeg.Profile {
Should we make the matching here case insensitive?

2020-06-23 06:49 UTC, jailuthra commented
For some reason the segmenter test case is failing (I guess it's unrelated to my changes because it fails on my local `master` build as well.

2020-06-23 20:01 UTC, j0sh commented on server/mediaserver_test.go
> +		{"name": "passthru_fps", "bitrate": 890, "width": 789, "height": 654, "profile": "H264ConstrainedHigh"}]}`)
TeSt FoR mIxEd CaSe?

2020-06-23 20:01 UTC, j0sh commented on server/mediaserver_test.go
> +		{"name": "passthru_fps", "bitrate": 890, "width": 789, "height": 654, "profile": "H264ConstrainedHigh"}]}`)
Actually it already *is* mixed case....!!

2020-06-23 20:49 UTC, j0sh approved these changes
LGTM 🚢 

Added some back-compat regression tests here https://gist.github.com/j0sh/9d884a19bb92e504092e71fd19d812e5#file-profiles-standalone-sh and https://gist.github.com/j0sh/9d884a19bb92e504092e71fd19d812e5#file-profiles-sh , things seem to work nicely.

2020-06-24 01:03 UTC, merged