Root cause for B's HTTP 500 responses
livepeer/go-livepeer pull request #1667
Opened 2020-11-24 19:26 UTC by jailuthra

**What does this pull request do? Explain your changes. (required)**

Figure out cause of #1665 

**Specific updates (required)**

- Log the JSON video profile parsing errors

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Checklist:**

- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [ ] All tests in `./test.sh` pass

2020-11-24 19:31 UTC, yondonfu approved these changes

2020-11-24 21:14 UTC, darkdarkdragon requested changes

2020-11-24 21:14 UTC, darkdarkdragon commented on server/mediaserver.go
> +				glog.Error("Failed to parse JSON video profile ", err)
```suggestion
				glog.Errorf("Failed to parse JSON video profile err=v%", err)
```

2020-11-25 15:43 UTC, jailuthra commented
Even though the error I was seeing in staging was most probably caused due to "Manifest already exists" as @darkdarkdragon mentioned here https://github.com/livepeer/go-livepeer/issues/1665#issuecomment-733234932

Still keeping this PR and increasing scope by improving other logs around RTMP stream ID creation as well. Many error logs in that method did not have any parameters like streamID or manifestID thus were hard to find in papertrail.

2020-11-25 19:06 UTC, darkdarkdragon requested changes

2020-11-25 19:06 UTC, darkdarkdragon commented on server/mediaserver.go
> +			glog.Errorf("Manifest %v already exists for streamID url=%s", mid, url.String())
```suggestion
			glog.Errorf("Manifest manifestID=%v already exists for streamID url=%s", mid, url.String())
```

2020-11-25 20:11 UTC, darkdarkdragon approved these changes
LGTM

2020-11-25 20:13 UTC, merged