Yf/orch metrics
livepeer/go-livepeer pull request #1670
Opened 2020-11-26 15:20 UTC by yondonfu

**What does this pull request do? Explain your changes. (required)**

Record and log the following metrics on O:
- Source segment duration
- Download time for source segment
- Transcode score for a segment which is defined as source segment duration / transcode time

B downloads the transcoded results from O separately and the associated HTTP handler lives in LPMS so I did not try to add metrics instrumentation there as well. As a result, this PR does not include the ability to measure the ratio between source segment duration and round trip time from O's POV.

A few other minor updates:
- 1702ba5 uses a NodeType type instead of a string in the `monitor` package. I felt that this would be less prone to error when writing conditionals based on the current node type as is done in 7a05697 which skips extra state tracking code in `SegmentEmerged` if the function is used for a node type other than a broadcaster
- 321f5d0 tweaks the view distribution for the source segment duration metric to make the percentile graph of source segment duration easier to understand

**Specific updates (required)**

See commit history.

**How did you test each of these updates (required)**

Tested manually.

**Does this pull request close any open issues?**

Fixes #1661 

**Checklist:**

- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

2020-11-26 18:06 UTC, darkdarkdragon requested changes
One small change
and not for the future: we're using `dur=` in logs both for segment's duration and network transfer duration. I think it would be good to separate them, use `segDur=` for example for segment's duration (not in this PR of course).

2020-11-26 18:06 UTC, darkdarkdragon commented on server/segment_rpc.go
> +		monitor.SegmentTranscoded(nonce, seg.SeqNo, time.Duration(seg.Duration)*time.Second, transcodeDur, common.ProfilesNames(params.Profiles))
```suggestion
		monitor.SegmentTranscoded(nonce, seg.SeqNo, time.Duration(seg.Duration*float64(time.Second)), transcodeDur, common.ProfilesNames(params.Profiles))
```

2020-11-27 14:35 UTC, yondonfu commented on server/segment_rpc.go
> +		monitor.SegmentTranscoded(nonce, seg.SeqNo, time.Duration(seg.Duration)*time.Second, transcodeDur, common.ProfilesNames(params.Profiles))
Fixed in 91b3825

2020-11-27 14:35 UTC, yondonfu commented
Fixed a `monitor` package test in 58ffeed that was failing due to the broadcaster only conditional check in `SegmentEmerged`.

2020-11-27 18:01 UTC, darkdarkdragon approved these changes
LGTM

2020-11-27 22:31 UTC, merged