Prometheus metrics for recording feature
livepeer/go-livepeer pull request #1710
Opened 2020-12-17 01:09 UTC by darkdarkdragon

**What does this pull request do? Explain your changes. (required)**
Prometheus metrics for recording feature
- recording_save_errors: number of errors during save to the recording OS
- recording_saved_segments: number of segments saved to the recording OS
- recording_save_latency: time takes to save segment to OS
- also marked "segment_transcoded_appeared_total" and  "segment_source_appeared_total" metrics with with "segment type" tag which
  can be "regular" (streams with recoding disabled) and "rec" (streams with recording enabled)

**Specific updates (required)**
added new metics

**How did you test each of these updates (required)**
Manual

**Does this pull request close any open issues?**
Fixes #1709

**Checklist:**

- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [ ] All tests in `./test.sh` pass

2020-12-18 23:00 UTC, yondonfu requested changes

2020-12-18 23:00 UTC, yondonfu commented on monitor/census.go
> +		mRecordingSegmentsSaved       *stats.Int64Measure
Not needed?

2020-12-18 23:59 UTC, darkdarkdragon commented on monitor/census.go
> +		mRecordingSegmentsSaved       *stats.Int64Measure
Fixed in 17583a1839da199a1dad9666031569de867260d8

2020-12-20 19:20 UTC, yondonfu approved these changes
LGTM after squashing

2020-12-20 22:26 UTC, merged