docker: libtensorflow 2.6.0 + CUDA 11.2.2
livepeer/go-livepeer pull request #2054
Opened 2021-10-12 13:19 UTC by yondonfu

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- 
- 
- 

**How did you test each of these updates (required)**

**Does this pull request close any open issues?**

**Checklist:**

- [ ] Read the [contribution guide](./doc/contributing.md)
- [ ] `make` runs successfully
- [ ] All tests in `./test.sh` pass
- [ ] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

2021-10-12 16:14 UTC, iameli approved these changes
LGTM with a caveat

2021-10-12 16:14 UTC, iameli commented on docker/Dockerfile.build-linux
> +FROM ubuntu:18.04
Note that this will likely cause go-livepeer to stop working on Ubuntu versions earlier than 18.04, as well as other distributions around that era, due to incompatibilities in the glibc version. I don't have strong feelings about that, just pointing out that's why this was set to 16.04 in the first place.

2021-10-12 18:36 UTC, yondonfu commented on docker/Dockerfile.build-linux
> +FROM ubuntu:18.04
Ah yeah thanks for flagging. We already build release binaries on 18.04 in the [Linux GH action](https://github.com/livepeer/go-livepeer/blob/e1518db8fb0350c520c6b304a1fb7046380dc3da/.github/workflows/linux.yml#L9) so I think matching with that should be ok.

2021-10-15 04:02 UTC, iameli requested changes
Using this branch for servers that require it, please do not merge until we've completed upgrades 😁

2022-04-25 14:09 UTC, thomshutt commented
@iameli @yondonfu Safe to fix up the conflicts here and merge now?

2023-01-09 14:43 UTC, closed without merging