broadcaster: fast verification frequency
livepeer/go-livepeer pull request #2056
Opened 2021-10-14 12:32 UTC by jailuthra

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**

- https://github.com/livepeer/go-livepeer/pull/2056/commits/59f43283b68dfd2734b9c578ea09b7026ecc9146 If the verificationFreq > 0 we should ask the Os to generate perceptual hashes, and download those hashes, regardless of how many Os are available or if we can even compare those hashes.
- https://github.com/livepeer/go-livepeer/pull/2056/commits/f2c156fee1ef59ed507a09cfc53cd644e0b98512 Once a session is verified, we use it for subsequent segments, as long as it is selected in the 3 sessions returned from the pools.
- https://github.com/livepeer/go-livepeer/pull/2056/commits/25373bda1fcd603b77892ba8ba2727a2b99ab684 Instead of sticking to a verified orchestrator throughout the stream, we run verification probabilistically on 1/VerificationFreq segments.
- https://github.com/livepeer/go-livepeer/pull/2056/commits/a73a85ec5c3da1ef95bb501554bb645113c83d97 If fast verification is disabled, default to selecting from untrusted pool first, only switching to trusted pool if no untrusted Os are available.

**How did you test each of these updates (required)**

Local end-to-end testing as described in https://github.com/livepeer/internal-project-tracking/issues/183

**Does this pull request close any open issues?**

Fixes #2033 

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [ ] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

2021-10-19 20:59 UTC, yondonfu requested changes

2021-10-19 20:59 UTC, yondonfu commented on server/broadcast.go
> +		verifiedSession:  nil,
Can be omitted because `verifiedSession` will be default to nil.

2021-10-19 20:59 UTC, yondonfu commented on server/broadcast.go
> +		// - It is present in the 3 sessions returned by the selector
What's the rationale for not just always returning the verified session if one exists?

Could the following be a simplification to the logic here?

```
// Always return multiple sessions if fast verification should be run
if common.RandomUintUnder(bsm.VerificationFreq) < 0 {
    sessions := bsm.trustedPool.selectSessions(1)
    untrustedSessions := bsm.untrustedPool.selectSessions(2)
    return append(sessions, untrustedSessions...), true
}

// If fast verification is enabled and fast verification does not need to be run return the verified session
if bsm.VerificationFreq > 0 && bsm.verifiedSession != nil {
    return bsm.verifiedSession, true
}

// Default to selecting from untrusted pool
sessions := bsm.untrustedPool.selectSession(1)
if len(sessions) <= 0 {
    sessions = bsm.trustedPool.selectSessions(1)
}

return sessions, false
```

2021-10-19 20:59 UTC, yondonfu commented on server/broadcast.go
> +			glog.V(common.DEBUG).Infof("Reusing verified orchestrator sess=%v", bsm.verifiedSession.OrchestratorInfo.Transcoder)
```suggestion
			glog.V(common.DEBUG).Infof("Reusing verified orch=%v", bsm.verifiedSession.OrchestratorInfo.Transcoder)
```

2021-10-19 20:59 UTC, yondonfu commented on common/util.go
> +var RandomUintUnder = func(max uint) uint {
What's the rationale for defining this as a package var? Is the intent to stub this out in unit tests?

2021-10-20 06:42 UTC, jailuthra commented on server/broadcast.go
> +		// - It is present in the 3 sessions returned by the selector
I did something similar initially, but if the `verifiedSession` went offline while we were solely relying on it, it lead to transcoding requests for multiple segments timing out. Things only recovered after a periodic refresh or the probabilistic draw for verification.

A possible way to fix it was to manually set `verifiedSession = nil` if we remove and suspend an orchestrator `sess == verifiedSession` due to a failed or timed out transcode. This would lead to a fresh set of `selectSession` calls immediately for the next segment.

But ultimately I ended up with the current solution, to not scatter the logic of setting/unsetting `verifiedSession` at multiple places.

By calling `pool.selectSessions(int)` for every segment, and verifying that our `verifiedSession` is in there, we ensure that it's alive and wasn't suspended for last segment. And the pool selectors anyway try to stick to `lastSessions` so this doesn't lead to a lot of switches.

```
// Default to selecting from untrusted pool
sessions := bsm.untrustedPool.selectSession(1)
if len(sessions) <= 0 {
    sessions = bsm.trustedPool.selectSessions(1)
}
```

^ Will fix this though, thanks!

2021-10-20 06:51 UTC, jailuthra commented on common/util.go
> +var RandomUintUnder = func(max uint) uint {
Yes that was the initial rationale, although still a TODO to update the unit test for the selection logic. Will fix.

2021-10-20 14:34 UTC, darkdarkdragon requested changes
Small comment, otherwise looks good.

2021-10-20 14:34 UTC, darkdarkdragon commented on server/broadcast.go
> +				bsm.completeSession(sess)
Can we create `completeSessionLocked` function which doesn't do locking inside?

2021-10-20 19:49 UTC, yondonfu commented on server/broadcast.go
> +				bsm.sessLock.Lock()
Is this a problem if we lock here after the loop completes? Could there be another call to a function that needs to call `bsm.sessLock.Lock()` after this loop completes that will block since `sessLock` is left in a locked state?

2021-10-21 06:04 UTC, jailuthra commented on server/broadcast.go
> +				bsm.sessLock.Lock()
`sessLock` should get unlocked a few lines below when we return from this function, due to the `defer bsm.sessLock.Unlock()` at the start of the function.

Regardless, I like Ivan's idea above for having a `completeSession` method that does not do locking inside, to prevent this weird looking call. Will fix.

2021-10-21 07:23 UTC, jailuthra commented on server/broadcast.go
> +				bsm.completeSession(sess)
Fixed

2021-10-21 13:19 UTC, yondonfu approved these changes
LGTM

2021-10-21 13:41 UTC, merged