Transcoder capabilities discovery and validation
livepeer/go-livepeer pull request #2150
Opened 2021-12-23 12:52 UTC by cyberj0g

**What does this pull request do? Explain your changes. (required)**

**Specific updates (required)**
* add capability test function which is run on node startup
* add logic to select transcoder according to capabilities in O-T mode
* add logic to validate capabilities in OT mode 

**How did you test each of these updates (required)**
Ran tests

**Does this pull request close any open issues?**
(https://github.com/livepeer/go-livepeer/issues/2123)

**Checklist:**

- [X] Read the [contribution guide](./doc/contributing.md)
- [X] `make` runs successfully
- [X] All tests in `./test.sh` pass
- [n/a] README and other documentation updated
- [n/a] [Pending changelog](./CHANGELOG_PENDING.md) updated

**Additional notes:**
One missing piece is automatic capability (codec) detection from segment. Currently, if segment is encoded with codec, for which T doesn't support decoding - and decoding capability is not explicitly requested, it will bypass capability-based T selection logic and may fail, even if O has Ts which could decode it. Should `go-livepeer` has such segment codec check (at which point?), or it's best to handle on MistServer side?

2022-01-21 12:47 UTC, oscar-davids approved these changes
LGTM!

2022-01-21 19:03 UTC, cyberj0g commented
Non-obvious quirk on multi-GPU system I just realized: there's no GPU-level segment scheduling logic, and capability discovery will provide a list of capabilities from less capable GPU, so if user has a rig with 5 x RTX 3090 and 1 GTX 745 to hook up the monitor, no codecs except H.264 would show up in capabilities, unless `-nvidia` argument excludes latter GPU. It worth documenting.

2022-02-02 04:14 UTC, darkdarkdragon requested changes

2022-02-02 04:14 UTC, darkdarkdragon commented on core/transcoder.go
> -		// "145x1" is the minimal resolution that succeeds on Windows, so use "145x145"
Can we put this comment back?

2022-02-02 04:14 UTC, darkdarkdragon commented on core/transcoder.go
> +				// transcode in 3 sessions which is a maximum on consumer Nvidia GPU with official driver
Our test intentionally used four output renditions - to let use know about problem at the startup time, not when user started to get real work on production node.

2022-02-02 04:14 UTC, darkdarkdragon commented on server/ot_rpc.go
> +	if n.Capabilities!=nil && !md.Caps.CompatibleWith(n.Capabilities.ToNetCapabilities()) {
Can we `gofmt` this?

2022-02-02 04:14 UTC, darkdarkdragon commented on core/orchestrator.go
> +			if caps == nil || caps.bitstring.CompatibleWith(rtm.remoteTranscoders[i].capabilities.bitstring) {
What will happen if old transcoder which does not present capabilities will be connected to that orchestrator?

2022-02-02 04:14 UTC, darkdarkdragon commented on cmd/livepeer/livepeer.go
> +		n.Capabilities = core.NewCapabilities(transcoderCaps, core.MandatoryOCapabilities())
That means that standalone O (which does not do transcoding) will advertise only default capabilities?

2022-02-02 10:20 UTC, cyberj0g reviewed
Thanks for review, all comments addressed.

2022-02-02 10:20 UTC, cyberj0g commented on cmd/livepeer/livepeer.go
> +		n.Capabilities = core.NewCapabilities(transcoderCaps, core.MandatoryOCapabilities())
Yes. Updating of O capabilities when new T connects is not addressed in this PR, as well as B support for such case. Added [comment](https://github.com/livepeer/go-livepeer/issues/2123#issuecomment-1027782218) to issue.

2022-02-02 10:20 UTC, cyberj0g commented on core/transcoder.go
> +				// transcode in 3 sessions which is a maximum on consumer Nvidia GPU with official driver
Ok, got it, changed it back to 4 sessions. IIRC the error message without patch won't be verbose, something like `Out of memory`. Is there section in docs which covers possible solutions to this on consumer GPUs?

2022-02-02 10:20 UTC, cyberj0g commented on core/transcoder.go
> -		// "145x1" is the minimal resolution that succeeds on Windows, so use "145x145"
Moved it to `capabilities.go` where test segment structure is.

2022-02-02 10:20 UTC, cyberj0g commented on server/ot_rpc.go
> +	if n.Capabilities!=nil && !md.Caps.CompatibleWith(n.Capabilities.ToNetCapabilities()) {
Done.

2022-02-02 10:21 UTC, cyberj0g commented on core/orchestrator.go
> +			if caps == nil || caps.bitstring.CompatibleWith(rtm.remoteTranscoders[i].capabilities.bitstring) {
Good catch, addressed it in `ot_rpc.go`.

2022-02-02 19:00 UTC, darkdarkdragon commented on core/transcoder.go
> +				// transcode in 3 sessions which is a maximum on consumer Nvidia GPU with official driver
I know, error message is confusing.
> Is there section in docs which covers possible solutions to this on consumer GPUs?

I'm not sure we want to cover this in our docs - patching drivers is in grey zone from legal viewpoint, so we don't want to encourage it.

2022-02-02 20:06 UTC, darkdarkdragon requested changes

2022-02-02 20:06 UTC, darkdarkdragon commented on server/ot_rpc.go
> +		return
you need to call `sendTranscodeResult` before return.
Also `err` is nil here, so I think we should define new error to return here.

2022-02-03 08:44 UTC, cyberj0g commented on server/ot_rpc.go
> +		return
Fixed.

2022-02-03 15:20 UTC, darkdarkdragon approved these changes
LGTM after squash/rebase

2022-02-07 10:08 UTC, merged