FFmpeg will return "ENODEV" instead of "AVERROR_UNKNOWN"
livepeer/go-livepeer pull request #2151
Opened 2021-12-24 18:32 UTC by JamesWanglf

**What does this pull request do? Explain your changes. (required)**
Since GPU transcoding test fails in LPMS, I have modified FFmpeg to return "ENODEV" error code instead of "AVERROR_UNKNOWN" if the invalid GPU device number is input.

**Specific updates (required)**
- I just updated the commit id for FFmpeg.

2021-12-27 06:56 UTC, cyberj0g requested changes
It looks like commit merging the PR is [e0eebeeeddf863f72da0232f9dddc05200340560](https://github.com/livepeer/FFmpeg/commit/e0eebeeeddf863f72da0232f9dddc05200340560)?

2021-12-27 08:54 UTC, cyberj0g approved these changes

2021-12-29 09:15 UTC, oscar-davids approved these changes

2021-12-30 14:54 UTC, yondonfu commented
Looks like the Linux Tensorflow CI build failed for some reason. Just restarted it to see if it was just a flaky build.

2022-01-10 15:28 UTC, merged