Minimum Viable Contributing Guide + Readme updates
livepeer/go-livepeer pull request #2192
Opened 2022-01-19 17:19 UTC by hthillman

**What does this pull request do? Explain your changes. (required)**
Updates the readme, adds a contributing guide, and makes some minor updates to documentation structure

**Specific updates (required)**
add CONTRIBUTING.md
update README.md
move changelog instructions to CONTRIBUTING.md

**How did you test each of these updates (required)**
the easiest way to review is probably to jump over to https://github.com/livepeer/go-livepeer/tree/hh-contributing-guide.

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [x] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

2022-01-26 21:19 UTC, hthillman commented
@yondonfu and/or @iameli can i get a review here? main concerns are probably re: the contribution guide

2022-01-27 00:46 UTC, yondonfu requested changes
Looks great! Just a few comments about links, but generally this is 👌 👌

2022-01-27 00:46 UTC, yondonfu commented on CONTRIBUTING.md
> +[bug](https://github.com/livepeer/go-livepeer/labels/good%20first%20issue)
Should this link filter for the bug label?

2022-01-27 00:46 UTC, yondonfu commented on CONTRIBUTING.md
> +[feature request](https://github.com/livepeer/go-livepeer/labels/help%20wanted).
Should this link filter for the feature request label?

2022-01-27 00:46 UTC, yondonfu commented on CONTRIBUTING.md
> +    [starting a discussion](https://github.com/livepeer/go-livepeer/issues/new/choose)
Should this link to the creation option under the "Discussion" tab of the repo?

2022-01-27 00:46 UTC, yondonfu commented on README.md
> +[![go-livepeer](https://user-images.githubusercontent.com/555740/117340053-78210e80-ae6e-11eb-892c-d98085fe6824.png)](https://github.com/livepeer/go-livepeer)
Niiiiiiiice

2022-01-27 17:42 UTC, yondonfu approved these changes
LGTM! Can you squash these commits before merging?

2022-01-27 23:57 UTC, merged