ai: Update llm pipeline
livepeer/go-livepeer pull request #3336
Opened 2024-12-29 04:43 UTC by ad-astra-video

**What does this pull request do? Explain your changes. (required)**

Updates go-livepeer for LLM pipeline updates for new response format.

Adds in validation of LLM request to gateway provided in #3204

Note: checked box to allow edits by maintainers to help expedite with timezone difference. Feel free to push any updates needed to branch.

Requires ai-worker https://github.com/livepeer/ai-worker/pull/387 to be merged
**Specific updates (required)**

- Updates needed for ai-worker changes to LLM request and response formats

**How did you test each of these updates (required)**

Built docker image locally for `livepeer/ai-runner:llm` and `livepeer/go-livepeer` to test streaming and non-streaming responses

**Does this pull request close any open issues?**

No

**Checklist:**

- [X] Read the [contribution guide](./CONTRIBUTING.md)
- [X] `make` runs successfully
- [ ] All tests in `./test.sh` pass
- [ ] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

2024-12-30 16:17 UTC, ad-astra-video commented
I will update `go.mod` when we get the second PR merged on ai-worker and new version tagged so can pull in final updates from ai-worker.

2024-12-30 23:29 UTC, kyriediculous commented on go.mod
> +replace github.com/livepeer/ai-worker => ./ai-worker
Seems like we have to update the ai-worker dependency still using `go get github.com/livepeer/ai-worker`

2025-01-02 12:43 UTC, leszko reviewed
Added 2 comments. Please also check if CI passes.

2025-01-02 12:43 UTC, leszko commented on server/ai_worker_test.go
> +		msgs = append(msgs, worker.LLMMessage{Role: "system", Content: "you are a robot"})
What are these messages? Prompts? Then, shouldn't they come from user's input?

2025-01-02 12:43 UTC, leszko commented on go.mod
> +replace github.com/livepeer/ai-worker => ./ai-worker
Yeah, we need to update this before merging.

2025-01-02 16:27 UTC, ad-astra-video commented on server/ai_worker_test.go
> +		msgs = append(msgs, worker.LLMMessage{Role: "system", Content: "you are a robot"})
These are in tests so that we can run tests with basic inputs.

2025-01-03 09:20 UTC, leszko commented on server/ai_worker_test.go
> +		msgs = append(msgs, worker.LLMMessage{Role: "system", Content: "you are a robot"})
ahh, ok

2025-01-03 09:49 UTC, leszko requested changes, later dismissed
@ad-astra-video The PR looks fine, but I see CI is failing, could you check?

https://github.com/livepeer/go-livepeer/actions/runs/12532555474/job/34951389606?pr=3336

2025-01-07 22:30 UTC, victorges approved these changes
LGTM but remember to update go.mod before merging

2025-01-07 22:30 UTC, victorges commented on core/ai_worker.go
> +	res, err := orch.node.AIWorkerManager.Process(ctx, requestID, "llm", *req.Model, "", AIJobRequestData{Request: req})
Don't we use `ModelId` (`model_id`) in all APIs? Any reason to use a different field for LLMs?

2025-01-07 22:30 UTC, victorges commented on go.mod
> +replace github.com/livepeer/ai-worker => ./ai-worker
Tip: You can make this PR not fail on CI (and if you accidentally merge it) by updating the `go.mod` with actual references in the target repo, even if they haven't been merged yet. A `replace` will never work on CI.

e.g. `go get -u github.com/livepeer/ai-worker@c3f347b`
to update to the latest commit on https://github.com/livepeer/ai-worker/pull/387

2025-01-07 22:30 UTC, victorges commented on server/ai_mediaserver.go
> +		if req.Model == nil || req.Messages == nil || req.Stream == nil || req.MaxTokens == nil {
I guess we can close https://github.com/livepeer/go-livepeer/pull/3204?

2025-01-13 16:57 UTC, ad-astra-video commented on core/ai_worker.go
> +	res, err := orch.node.AIWorkerManager.Process(ctx, requestID, "llm", *req.Model, "", AIJobRequestData{Request: req})
`model` is used in llm pipeline to follow the open ai spec closer which I think makes sense for this pipeline.

https://platform.openai.com/docs/guides/text-generation

2025-01-14 07:58 UTC, ad-astra-video commented on server/ai_mediaserver.go
> +		if req.Model == nil || req.Messages == nil || req.Stream == nil || req.MaxTokens == nil {
Yes we can. I tested removing all these items from the request and confirmed did not seg fault.

Also added a check that `req.Messages` is not empty because it would seg fault the worker if no messages were sent in the request.

2025-01-14 07:59 UTC, ad-astra-video commented on go.mod
> +replace github.com/livepeer/ai-worker => ./ai-worker
Updated go.mod to `github.com/livepeer/ai-worker v0.13.1`

2025-01-14 08:09 UTC, ad-astra-video commented
@rickstaa @kyriediculous Updated PR for latest updates in LLM pipeline. Please let me know if anything want changed.  Built and tested locally end-to-end with no issues.

2025-01-24 18:56 UTC, rickstaa approved these changes
LGTM, will run one production test and merge.

2025-01-27 21:22 UTC, merged