Store receipts, submit claims for recovered receipts.
livepeer/go-livepeer pull request #410
Opened 2018-05-03 05:39 UTC by j0sh

Note that https://github.com/livepeer/go-livepeer/commit/2dbed04baaf9bf03142895175f46f7c5f9a4a6ca fixes https://github.com/livepeer/go-livepeer/issues/352 . If the claims process fails any time after submitting the tx, the segments will have to be cleaned up from disk manually (we don't yet attempt to fixup such claim transactions, either). See the note here: https://github.com/livepeer/go-livepeer/commit/2dbed04baaf9bf03142895175f46f7c5f9a4a6ca#diff-a776aba743c0cf86c5c34fc5236506eeR493

2018-05-03 21:50 UTC, ericxtang requested changes

2018-05-03 21:50 UTC, ericxtang commented on common/db.go
> +func (db *DB) ReceiptsByClaim(claimID int64, jobID *big.Int) ([]string, error) {
Looks like this is only getting the location for the broadcasted file locations.  Maybe rename to `ReceiptBCastFilesByClaim`?

2018-05-03 22:02 UTC, j0sh commented on common/db.go
> +func (db *DB) ReceiptsByClaim(claimID int64, jobID *big.Int) ([]string, error) {
Sure. Also realized this function was in the wrong commit. Fixed on both counts :+1:

2018-05-04 15:37 UTC, ericxtang approved these changes
🚢

2018-05-04 16:50 UTC, yondonfu approved these changes

2018-05-04 17:01 UTC, closed without merging