On-chain job-claim-verify-distributefees
livepeer/go-livepeer pull request #70
Opened 2017-08-24 19:30 UTC by yondonfu

Refactored the `claimmanager.go` and `rewardmanager.go` to work with the new client architecture. The LP node can now act as an on-chain transcoder. When a node is started in transcoder mode for the first time, the node will register the user ETH account as a transcoder and prompt the user for an amount to bond to itself. Afterwords, the user will become an active transcoder the following round. The transcoding node listens for NewJob events that include it as an elected transcoder. When a broadcaster ends a stream, the transcoder will claim segments on-chain, verify the necessary segments and call distribute fees. The broadcaster will try to withdraw its deposit.

2017-08-24 21:54 UTC, ericxtang requested changes
Left some comments

2017-08-24 21:54 UTC, ericxtang commented on cmd/livepeer/livepeer.go
> +	glog.Infof("Bootnode? %v", *bootnode)
remove

2017-08-24 21:54 UTC, ericxtang commented on cmd/livepeer/livepeer.go
> +				fmt.Println("You are not registered as a transcoder. To register and become a candidate transcoder please bond some tokens: ")
let's use glog.Infof

2017-08-24 21:54 UTC, ericxtang commented on cmd/livepeer/livepeer.go
> +				var bondAmount int
can we do uint here?

2017-08-24 21:54 UTC, ericxtang commented on cmd/livepeer/livepeer.go
> +			}
I think we should exit if `registerAndSetupTranscoder` or `setupTranscoder` fail

2017-08-24 21:54 UTC, ericxtang commented on cmd/livepeer/livepeer.go
>  func txDataToVideoProfile(txData string) []types.VideoProfile {
We should add error checking here - it's possible the job's video profiles aren't defined on this node.

2017-08-24 21:54 UTC, ericxtang commented on core/livepeernode.go
> +			// if ssb, err := SignedSegmentToBytes(SignedSegment{Seg: *seg, Sig: nil}); err == nil {
remove

2017-08-24 21:54 UTC, ericxtang commented on eth/client.go
> +	// transactOpts.GasPrice = big.NewInt(4000000000)
Should we be able to set the gas price on the node level?

2017-08-24 21:54 UTC, ericxtang commented on eth/client.go
> +		// glog.Infof("Gas used for tx %v: %v", receipt.TxHash.Hex(), receipt.GasUsed)
Do we still need this?

2017-08-24 21:54 UTC, ericxtang commented on server/mediaserver.go
> +				// err = hlsStrm.AddHLSSegment(hlsStrmID.String(), &stream.HLSSegment{Name: fmt.Sprintf("%v_eof", hlsStrmID), EOF: true})
Remove

2017-08-24 21:54 UTC, ericxtang commented on server/mediaserver.go
> +				// if err != nil {
Remove

2017-08-25 21:00 UTC, yondonfu commented
Some additions:
- Added `gasPrice` flag that sets gas price used for ETH transactions
- If the `deposit` flag is > 0, the user will be presented a prompt confirming the deposit amount
- Every time a transcoder node receives a segment from a broadcast stream, before transcoding the segment for each video profile, it checks the broadcaster deposit. If the broadcaster deposit does not have enough funds for even a single transcoded segment, the transcoder stops and claims work there. If the broadcaster deposit has enough funds for at least a single transcoded segment, the transcoder will create and broadcast the transcoded segments.

2017-08-28 15:24 UTC, ericxtang commented
Looks good.  🚢  after resolving conflict.

2017-08-28 15:25 UTC, ericxtang approved these changes

2017-08-28 15:29 UTC, merged