Structured Ingest URLs
livepeer/go-livepeer pull request #798
Opened 2019-03-22 16:40 UTC by j0sh

**What does this pull request do? Explain your changes. (required)**
Uses RTMP URL by default to construct manifest ID and stream key.

**Specific updates (required)**

- https://github.com/livepeer/go-livepeer/commit/bcd4202eb34912f4527ad66ccf444cad600b64f9 Extract ManifestID from URL path. Note that this follows the scheme outlined in https://github.com/livepeer/go-livepeer/issues/791#issuecomment-472572559 where the user can incorporate an optional `/stream/` prefix into the path.

- https://github.com/livepeer/go-livepeer/commit/4bd3167d2f1d11a1ff34dd794540c907ee6d58e9 Extract stream key from URL path. Also return stream keys from the auth webhook. If no key is provided, then a random key is generated (following the old behavior).

- Removed the support for looking up the manifestID via the query parameter. This is technically a breaking change; the test harness and any client scripts that use the query parameter will have to change. cc @ya7ya @darkdarkdragon This does *not* affect webhooks, which are still free to use any URL structure they please, including query parameters, as shown in our [simple auth server](https://github.com/livepeer/go-livepeer/blob/master/cmd/simple_auth_server/simple_auth_server.go) example.

**How did you test each of these updates (required)**
Added unit testing, performed manual testing.

**Does this pull request close any open issues?**
Fixes https://github.com/livepeer/go-livepeer/issues/791
Fixes https://github.com/livepeer/go-livepeer/issues/764

**Checklist:**

- [x] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

2019-03-24 12:04 UTC, darkdarkdragon requested changes
I think we should at least state in the docs that feeding RTMP stream int
`rtmp://host/stream` will not yield stream to be available at
`http://host/stream/stream.m3u8` - this can be confusing.

2019-03-24 12:04 UTC, darkdarkdragon commented on doc/rtmpwebhookauth.md
> +    "manifestID": "ManifestIDString"
should be comma in the end

2019-03-25 21:19 UTC, j0sh commented on doc/rtmpwebhookauth.md
> +    "manifestID": "ManifestIDString"
Fixed

2019-03-25 21:24 UTC, j0sh commented
Expanded the documentation with a new page on ingest handling since explaining the `/stream/` handling seemed like too much detail for the README: https://github.com/livepeer/go-livepeer/pull/798/commits/19b045de0844e3cc758a9cb7962f215227662757

The doc also expands on the concept of protecting RTMP playback via stream keys, and documents a few other CLI flags that modify ingest behavior. (Although we really should have a single page that comprehensively documents all our CLI flags: https://github.com/livepeer/go-livepeer/issues/708 )

2019-03-25 21:32 UTC, darkdarkdragon commented
LGTM 🚢

2019-03-26 15:25 UTC, angyangie commented on doc/ingest.md
> +# Canonical Form
Really useful examples here!!

2019-03-26 15:26 UTC, angyangie approved these changes
LGTM!

2019-03-26 15:54 UTC, j0sh commented
@darkdarkdragon Github won't let me merge until you approve the changes, can that be done?

2019-03-26 17:56 UTC, darkdarkdragon approved these changes

2019-03-28 00:04 UTC, merged