cmd: fix keystore copy and pricePerUnit flag
livepeer/go-livepeer pull request #922
Opened 2019-06-17 22:26 UTC by kyriediculous

**What does this pull request do? Explain your changes. (required)**
- Prevents the generated scripts from erroring for `setup transcoder` by supplying `-pricePerUnit 1` flag
- Uses custom function to copy the temporary keystore directory to prevent OS specific restrictions on `os.Rename`

**Specific updates (required)**
- Added `-pricePerUnit 1` flag to `createRunScript`
- Added custom function copyDir, copyFile
- Added generated `.lpdev2` to `.gitignore`

**How did you test each of these updates (required)**
Ran devtools script for both transcoder and broadcaster

**Does this pull request close any open issues?**
Fixes #921 
Fixes #918

**Checklist:**
- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [ ] All tests in `./test.sh` pass

2019-06-18 20:15 UTC, darkdarkdragon requested changes

2019-06-18 20:15 UTC, darkdarkdragon commented on cmd/devtool/devtool.go
> +func copyDir(src, dst string) error {
This function removes source dir at the end, so probably better be called `moveDir`?

2019-06-18 20:15 UTC, darkdarkdragon commented on cmd/devtool/devtool.go
> +func copyFile(src, dst string, info os.FileInfo) error {
This function removes file at the end, so probably better be called `moveFile`?

2019-06-18 20:17 UTC, darkdarkdragon commented
@kyriediculous 
I've pushed over commit that fixes setting up of broadcaster to be able to do transcoding.
Other from two small comment PR looks good.

2019-06-18 23:29 UTC, kyriediculous commented
Made the requested changes and did some code cleanup. 

Will clean up commit history before merging.

2019-06-19 08:32 UTC, darkdarkdragon approved these changes
LGTM 🚢

2019-06-19 10:13 UTC, merged